/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_RRCConnectionSetupRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_RRCConnectionSetupComplete;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module RRC-ASN1-Module in ../RRCMessageModule.asn1 */
	&asn_DEF_RRCConnectionSetupRequest,	
	&asn_DEF_RRCConnectionSetupComplete,	
	0
};

