/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRC-ASN1-Module"
 * 	found in "../RRCMessageModule.asn1"
 * 	`asn1c -fcompound-names -gen-PER -pdu=auto`
 */

#ifndef	_RRCConnectionSetupRequest_H_
#define	_RRCConnectionSetupRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRCMessageHeader.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RRCConnectionSetupRequest */
typedef struct RRCConnectionSetupRequest {
	RRCMessageHeader_t	 messageHeader;
	OCTET_STRING_t	 mmeUEIdentity;
	OCTET_STRING_t	 sTMSI;
	OCTET_STRING_t	 cellIdentify;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionSetupRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionSetupRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _RRCConnectionSetupRequest_H_ */
#include <asn_internal.h>
