/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRC-ASN1-Module"
 * 	found in "../RRCMessageModule.asn1"
 * 	`asn1c -fcompound-names -gen-PER -pdu=auto`
 */

#ifndef	_RRCConnectionSetupComplete_H_
#define	_RRCConnectionSetupComplete_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRCMessageHeader.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RRCConnectionSetupComplete */
typedef struct RRCConnectionSetupComplete {
	RRCMessageHeader_t	 messageHeader;
	long	 integrityProtectionAlgorithm;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionSetupComplete_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionSetupComplete;

#ifdef __cplusplus
}
#endif

#endif	/* _RRCConnectionSetupComplete_H_ */
#include <asn_internal.h>
