/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRC-ASN1-Module"
 * 	found in "../RRCMessageModule.asn1"
 * 	`asn1c -fcompound-names -gen-PER -pdu=auto`
 */

#ifndef	_RRCMessageHeader_H_
#define	_RRCMessageHeader_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MessageType.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RRCMessageHeader */
typedef struct RRCMessageHeader {
	MessageType_t	 messageType;
	long	 messageLenght;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCMessageHeader_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCMessageHeader;

#ifdef __cplusplus
}
#endif

#endif	/* _RRCMessageHeader_H_ */
#include <asn_internal.h>
